//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainSimulator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrainSimulator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disabled {
            get {
                object obj = ResourceManager.GetObject("disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap employee {
            get {
                object obj = ResourceManager.GetObject("employee", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natalia
        ///Yanina
        ///Nelida
        ///Maria
        ///Vanesa
        ///Miriam
        ///Mirta
        ///Rosa
        ///Gina
        ///Oriana
        ///Carmen
        ///Paula
        ///Martina
        ///Gisel
        ///Gisella
        ///Antonella
        ///Veronica
        ///Viviana
        ///Susana
        ///Griselda
        ///Alejandra
        ///Marcela
        ///Carla
        ///Nayla
        ///Romina
        ///Erica
        ///Macarena
        ///Carina
        ///Cecilia
        ///Marta
        ///Brenda
        ///Florencia
        ///Fatima
        ///Johana
        ///Juana
        ///Rigoberta
        ///Rocio
        ///Agustina
        ///Mia
        ///Janet
        ///Celeste
        ///Daiana
        ///Lorena
        ///Norma
        ///Sandra
        ///Debora
        ///Andrea
        ///Julia
        ///Daniela
        ///Laura
        ///Mariana
        ///Milena
        ///Marianela
        ///Noelia
        ///Fernanda
        ///Teresa
        ///Gladis
        ///Tatiana
        ///Gabriela
        ///Graciela
        ///Soledad
        ///Sol
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FemaleNames {
            get {
                return ResourceManager.GetString("FemaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biasoli
        ///Gomez
        ///Lopez
        ///Lamanuzzi
        ///Garcia
        ///Gonzalez
        ///Fernandez
        ///Hernandez
        ///Martinez
        ///Sala
        ///Farias
        ///Mercado
        ///Barovero
        ///Chiarini
        ///Bottachi
        ///Sanchez
        ///Mammana
        ///Gallardo
        ///Ballester
        ///Tavella
        ///Magallanes
        ///Rusca
        ///Veron
        ///Cambiasso
        ///Rojas
        ///Pisculichi
        ///Vangioni
        ///Gutierrez
        ///Driussi
        ///Funes Mori
        ///Pezzella
        ///Haussmann
        ///Dantur
        ///Null
        ///Franco
        ///Galeano
        ///Morales
        ///Carrio
        ///Silvani
        ///Toresani
        ///Miglietti
        ///Goncalves
        ///Kranevitter
        ///Ponzio
        ///Peña
        ///Bravo
        ///Marco
        ///Marchioni
        ///Zsechet
        ///Valido
        ///Lobato
        ///.
        /// </summary>
        internal static string Lastnames {
            get {
                return ResourceManager.GetString("Lastnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andres
        ///Matias
        ///Hugo
        ///Javier
        ///Ricardo
        ///Martin
        ///Guillermo
        ///Pablo
        ///Juan
        ///Pedro
        ///Mariano
        ///Nicolas
        ///Ivan
        ///Miguel
        ///Leonardo
        ///Leandro
        ///Leonel
        ///Carlos
        ///Osvaldo
        ///Omar
        ///Alberto
        ///Roberto
        ///Ruben
        ///Hernan
        ///Emiliano
        ///Federico
        ///Fernando
        ///Rodrigo
        ///Rodolfo
        ///Eduardo
        ///Bautista
        ///Ignacio
        ///Jose
        ///Jorge
        ///Sebastian
        ///Adrian
        ///Julio
        ///Julian
        ///Victor
        ///Gaston
        ///Geronimo
        ///Ezequiel
        ///Laureano
        ///Diego
        ///Mauricio
        ///Maximo
        ///German
        ///Gerardo
        ///Gabriel
        ///Damian
        ///Bruno
        ///Francisco
        ///Cesar
        ///Lucas
        ///Leopoldo
        ///Alejandro
        ///Alex
        ///Alan
        ///Alexis
        ///Marcelo
        ///.
        /// </summary>
        internal static string MaleNames {
            get {
                return ResourceManager.GetString("MaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap officer {
            get {
                object obj = ResourceManager.GetObject("officer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rail {
            get {
                object obj = ResourceManager.GetObject("rail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap retired {
            get {
                object obj = ResourceManager.GetObject("retired", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap station1 {
            get {
                object obj = ResourceManager.GetObject("station1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap student {
            get {
                object obj = ResourceManager.GetObject("student", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap train {
            get {
                object obj = ResourceManager.GetObject("train", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
